/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package app;

import java.awt.Menu;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JFrame;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;


/**
 *
 * @author DELL
 */
public class employee_id extends javax.swing.JFrame {
    String eDB = "jdbc:mysql://localhost:3306/employee_id";
    String eUser="root";
    String ePassword = "";
    //private String employeeID;

    /** Creates new form employee_id */
    public employee_id() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        employeeid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        taxdeductible = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        netsalary = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        empname = new javax.swing.JLabel();
        reimbursement = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        bonusam = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        salarycut = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        leavedays = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        salary = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Salary Cut:");

        jLabel12.setText("jLabel12");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tax Deductable:");

        jLabel13.setText("jLabel13");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Net Salary:");

        jButton2.setText("Email");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Download");

        jButton4.setText("Back");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Employee Name:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Reimbursement:");

        jLabel11.setText("jLabel10");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Bonus Amount:");

        jLabel15.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PAYCHECK GENERATOR");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("EMPLOYEE LOGIN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Employee_ID:");

        employeeid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                employeeidKeyReleased(evt);
            }
        });

        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Salary Cut:");

        taxdeductible.setText("jLabel12");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Tax Deductable:");

        netsalary.setText("jLabel13");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Net Salary:");

        jButton5.setText("Email");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Download");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        empname.setText("jLabel8");

        reimbursement.setText("jLabel9");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Employee Name:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Reimbursement:");

        bonusam.setText("jLabel10");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Bonus Amount:");

        salarycut.setText("jLabel11");

        jButton7.setText("Reimbursement");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        leavedays.setText("Leave Days");
        leavedays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leavedaysActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Salary:");

        salary.setText("jLabel19");

        jButton8.setText("Bonus");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(195, 195, 195))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(employeeid, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(jLabel26)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel17))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salary)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(netsalary)
                        .addComponent(taxdeductible, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(salarycut)
                        .addComponent(bonusam))
                    .addComponent(reimbursement)
                    .addComponent(empname))
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(leavedays, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton6)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(employeeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empname)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(salary))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reimbursement)
                                .addGap(18, 18, 18)
                                .addComponent(bonusam)
                                .addGap(18, 18, 18)
                                .addComponent(salarycut)
                                .addGap(18, 18, 18)
                                .addComponent(taxdeductible)
                                .addGap(18, 18, 18)
                                .addComponent(netsalary))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leavedays, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private double calculateTotalReimbursement(int empId) {
        double totalReimbursement = 0.0;
        
        try {
            // Establish connection to the database
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/employee_id", "root", "");
            
            // Prepare the SQL statement to retrieve reimbursements for the given emp_id
            String sql = "SELECT reimbursement_val FROM reimbursement WHERE emp_id = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setInt(1, empId);

            // Execute the query
            ResultSet rs = stmt.executeQuery();

            // Iterate through the result set and sum up the reimbursement amounts
            while (rs.next()) {
                totalReimbursement += rs.getDouble("reimbursement_val");
            }

            // Close resources
            rs.close();
            stmt.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        
        return totalReimbursement;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String id = employeeid.getText();
            if (id.length() > 0) {
                String sql = "SELECT e.first_name, b.bonus_val, ld.final_deduct, s.salary " +
                             "FROM employee e " +
                             "INNER JOIN bonus b ON e.employee_id = b.emp_id " +
                             "INNER JOIN leave_days ld ON e.employee_id = ld.emp_id "+
                             "INNER JOIN salary s ON e.employee_id = s.emp_id " +   
                             "WHERE e.employee_id = ?";

                Connection con = DriverManager.getConnection(eDB, eUser, ePassword);
                PreparedStatement stmt = con.prepareStatement(sql);
                stmt.setString(1, id);
                ResultSet rs = stmt.executeQuery();

                if (rs.next()) {
                    String employeeName = rs.getString("first_name");
                    double bonusAmount = rs.getDouble("bonus_val");
                    double tdeduct = rs.getDouble("final_deduct");
                    double yearlySalary = rs.getDouble("salary");
                    
                    double totaltax=yearlySalary * 12;
                    double quarterlytax=totaltax / 4;
                    
                    double taxDeductiblePercentage = 0.0;
                    if (yearlySalary <= 250000) {
                        taxDeductiblePercentage = 0.0; // Exempted
                    } else if (yearlySalary <= 300000) {
                        taxDeductiblePercentage = 0.0; // Exempted
                    } else if (yearlySalary <= 500000) {
                        taxDeductiblePercentage = 0.05; // 5%
                    } else if (yearlySalary <= 600000) {
                        taxDeductiblePercentage = 0.05; // 5%
                    } else if (yearlySalary <= 900000) {
                        taxDeductiblePercentage = 0.10; // 10%
                    } else if (yearlySalary <= 1000000) {
                        taxDeductiblePercentage = 0.15; // 15%
                    } else if (yearlySalary <= 1200000) {
                        taxDeductiblePercentage = 0.15; // 15%
                    } else if (yearlySalary <= 1500000) {
                        taxDeductiblePercentage = 0.20; // 20%
                    } else {
                        taxDeductiblePercentage = 0.30; // 30%
                    }
                    
                    double taxDeductible = yearlySalary * taxDeductiblePercentage;
                    double totalReimbursement = calculateTotalReimbursement(Integer.parseInt(id));
                    
                    //employeeID=id;

                    empname.setText(employeeName);
                    bonusam.setText(String.valueOf(bonusAmount));
                    salarycut.setText(String.valueOf(tdeduct));
                    reimbursement.setText(String.valueOf(totalReimbursement));
                    salary.setText(String.valueOf(yearlySalary));
                    taxdeductible.setText(String.valueOf(taxDeductible));
                    netsalary.setText(String.valueOf((yearlySalary + bonusAmount) - (taxDeductible+tdeduct)));
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid credentials");
                    employeeid.setText("");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    
    
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void employeeidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeidKeyReleased
            if (employeeid.getText().length()==0) {
                    empname.setText("");
                    reimbursement.setText("");
                    bonusam.setText("");
                    salarycut.setText("");
                    taxdeductible.setText("");
                    netsalary.setText("");
            }
                // TODO add your handling code here:
    }//GEN-LAST:event_employeeidKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setVisible(false);
        new reimbursement().setVisible(true);
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void leavedaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leavedaysActionPerformed
        // TODO add your handling code here:
        //Leavedays leavedaysScreen = new Leavedays(getEmployeeID()); // Pass the employee ID to the constructor
        this.setVisible(false);
        new leavedays().setVisible(true);
        
    }//GEN-LAST:event_leavedaysActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new bonus().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String employeeID = employeeid.getText(); // Get the entered employee ID

    // Retrieve employee information based on the employee ID
        String ename = empname.getText();
        String sal = salary.getText();
        String reimburse = reimbursement.getText();
        String bamount = bonusam.getText();
        String sc = salarycut.getText();
        String taxd= taxdeductible.getText();
        String netsal = netsalary.getText();

        if (employeeID != null) {
            try {
                // Get the path to the Downloads directory
                String downloadsPath = "C:\\Users\\DELL\\Downloads\\";

                // Create a new PDF document
                Document document = new Document();

                // Provide the path where you want to save the generated PDF
                String fileName = downloadsPath + "SalarySlip_" + ename + ".pdf";
                PdfWriter.getInstance(document, new FileOutputStream(fileName));
                document.open();

                // Add employee information to the PDF
                document.add(new Paragraph("Employee ID: " + employeeID));
                document.add(new Paragraph("Name: " + ename));
                document.add(new Paragraph("Salary: " + sal));
                document.add(new Paragraph("Reimbursement: " + reimburse));
                document.add(new Paragraph("Bonus Amount: " + bamount));
                document.add(new Paragraph("Salary Cut: " + sc));
                document.add(new Paragraph("Tax Deductible: " + taxd));
                document.add(new Paragraph("Net Salary: " + netsal));

                // Close the document
                document.close();

                JOptionPane.showMessageDialog(this, "Salary slip downloaded successfully!");

            } catch (DocumentException | IOException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error downloading salary slip: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Employee ID is required!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee_id().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bonusam;
    private javax.swing.JTextField employeeid;
    private javax.swing.JLabel empname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton leavedays;
    private javax.swing.JLabel netsalary;
    private javax.swing.JLabel reimbursement;
    private javax.swing.JLabel salary;
    private javax.swing.JLabel salarycut;
    private javax.swing.JLabel taxdeductible;
    // End of variables declaration//GEN-END:variables

}
